<?php

/**
 * Ukz375199ontdgReviewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewTable extends Doctrine_Table implements iReviewTable
{
	private $langs = array( 'it' => 'italian', 'en' => 'english' );
	private $sorts = array( 'asc' => 'ASC', 'desc' => 'DESC' );
    /**
     * Returns an instance of this class.
     *
     * @return object Ukz375199ontdgReviewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Review');
    }
    
    public function getReviewsByLetter($letter, $options=array()){
    	$options = $this->checkOptions($options);
    	
    	$q = Doctrine_Query::create()
			->from("review R")
			->where("rlanguage = ?", $options['lang'])
			->andWhere("SUBSTR(R.title,1,1) = ?", $letter)
			->orderBy('R.title '.$options['sort'])
			;
		if ($options['page']) {
			$page = explode(',',$options['page']);
			$q->offset($page[0])->limit($page[1]);
		}
		return $q->execute();
    }

    public function getReviewsByKeyword($key, $options=array()){
    	$options = $this->checkOptions($options);
    	
    	$q = Doctrine_Query::create()
			->from("review R")
			->where("rlanguage = ?", $options['lang'])
			->andWhere("R.title LIKE  ?", '%'.$key.'%')
			->orderBy('R.title '.$options['sort'])
			;
		if ($options['page']) {
			$page = explode(',',$options['page']);
			$q->offset($page[0])->limit($page[1]);
		}
		return $q->execute();
    }
    
    private function checkOptions($options){
    	if (!($options['lang'] = $this->langs[$options['lang']]))
    		$options['lang'] = $this->langs['it'];    	

    	if (!($options['sort'] = $this->sorts[$options['sort']]))
    		$options['sort'] = $this->sorts['asc'];

    	if ($options['page']) {
    		$page = explode(',',$options['page']);
    		if (!(count($page)==2 && is_int((int)$page[0]) && is_int((int)$page[1])))
    			unset($options['page']);
    	}

    	return $options;
    }
}