<?php

/**
 * Token
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Token extends BaseToken
{
	public function isValid() {
		return $this->enabled;
	}
	
	public function enable() {
		$this->enabled = true;
		$this->save();
	}
	public function disable() {
		$this->enabled = 'false'; //non va altrimenti
		$this->save();
	}
	
	public function getToken(){
		return $this->token;
	}
	
	public function regenerate() {
		$this->token = $this->getUniqueRandomToken();
		$this->save();
	}
	
	private function getRandomToken() {
		$alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789';
		$n = strlen($alphabet);
		$out = '';
		for ($i=0; $i<20; $i++){
			$out .= substr($alphabet,rand(0,$n-1),1);
		}
		return $out;
	}
	
	public function preSave(){
		if (!$this->token) {			
			$this->token = $this->getUniqueRandomToken();
		}
	}
	private function getUniqueRandomToken(){
		$table = TokenTable::getInstance();
		$token = $this->getRandomToken();
		while($table->getByToken($token))
			$token = $this->getRandomToken();
		return $token;
	}

}